package com.zitlab.palmyra.xdbmd.jdbc.plugin;

public interface HsqlQuery {
	public static final String GET_IMPORTED_KEYS = "SELECT CURRENT_CATALOG as PKTABLE_CAT ,f.PKTABLE_SCHEM,f.PKTABLE_NAME ,f.PKCOLUMN_NAME ,f.FKTABLE_CAT ,f.FKTABLE_SCHEM ,f.FKTABLE_NAME ,f.FKCOLUMN_NAME ,f.KEY_SEQ ,f.UPDATE_RULE,f.DELETE_RULE,f.FK_NAME ,f.PK_NAME ,f.DEFERRABILITY  FROM INFORMATION_SCHEMA.SYSTEM_CROSSREFERENCE  f where PKTABLE_SCHEM= ? and PKTABLE_NAME = ?";
}
